"""Added storage model

Revision ID: 06003b460c7f
Revises: c416f4b721bf
Create Date: 2019-05-30 12:32:10.349770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06003b460c7f'
down_revision = 'c416f4b721bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=32), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('default', sa.String(length=255), nullable=True),
    sa.Column('modifier', sa.String(length=64), nullable=True),
    sa.Column('type_hasher', sa.String(length=255), nullable=True),
    sa.Column('type_key1', sa.String(length=255), nullable=True),
    sa.Column('type_key2', sa.String(length=255), nullable=True),
    sa.Column('type_value', sa.String(length=255), nullable=True),
    sa.Column('type_is_linked', sa.SmallInteger(), nullable=True),
    sa.Column('type_key2hasher', sa.String(length=255), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_storage_lookup'), 'runtime_storage', ['lookup'], unique=False)
    op.add_column('data_block', sa.Column('blocktime', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_accounts_new', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_events_extrinsic', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_events_finalization', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_events_module', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_events_system', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_extrinsics_error', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_extrinsics_signed', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_extrinsics_signedby_address', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_extrinsics_signedby_index', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_extrinsics_success', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('count_extrinsics_unsigned', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('data_block', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('data_block', sa.Column('full_day', sa.String(length=10), nullable=True))
    op.add_column('data_block', sa.Column('full_hour', sa.String(length=13), nullable=True))
    op.add_column('data_block', sa.Column('full_month', sa.String(length=7), nullable=True))
    op.add_column('data_block', sa.Column('full_week', sa.String(length=7), nullable=True))
    op.add_column('data_block', sa.Column('hour', sa.Integer(), nullable=True))
    op.add_column('data_block', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('data_block', sa.Column('parent_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('data_block', sa.Column('range10000', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('range100000', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('range1000000', sa.Integer(), nullable=False))
    op.add_column('data_block', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('data_block', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_data_event_block_id'), 'data_event', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_event_event_idx'), 'data_event', ['event_idx'], unique=False)
    op.add_column('data_extrinsic', sa.Column('account_idx', sa.Integer(), nullable=True))
    op.add_column('data_extrinsic', sa.Column('signedby_address', sa.SmallInteger(), nullable=False))
    op.add_column('data_extrinsic', sa.Column('signedby_index', sa.SmallInteger(), nullable=False))
    op.create_index(op.f('ix_data_extrinsic_account_idx'), 'data_extrinsic', ['account_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_extrinsic_account_idx'), table_name='data_extrinsic')
    op.drop_column('data_extrinsic', 'signedby_index')
    op.drop_column('data_extrinsic', 'signedby_address')
    op.drop_column('data_extrinsic', 'account_idx')
    op.drop_index(op.f('ix_data_event_event_idx'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_block_id'), table_name='data_event')
    op.drop_column('data_block', 'year')
    op.drop_column('data_block', 'week')
    op.drop_column('data_block', 'range1000000')
    op.drop_column('data_block', 'range100000')
    op.drop_column('data_block', 'range10000')
    op.drop_column('data_block', 'parent_datetime')
    op.drop_column('data_block', 'month')
    op.drop_column('data_block', 'hour')
    op.drop_column('data_block', 'full_week')
    op.drop_column('data_block', 'full_month')
    op.drop_column('data_block', 'full_hour')
    op.drop_column('data_block', 'full_day')
    op.drop_column('data_block', 'day')
    op.drop_column('data_block', 'datetime')
    op.drop_column('data_block', 'count_extrinsics_unsigned')
    op.drop_column('data_block', 'count_extrinsics_success')
    op.drop_column('data_block', 'count_extrinsics_signedby_index')
    op.drop_column('data_block', 'count_extrinsics_signedby_address')
    op.drop_column('data_block', 'count_extrinsics_signed')
    op.drop_column('data_block', 'count_extrinsics_error')
    op.drop_column('data_block', 'count_events_system')
    op.drop_column('data_block', 'count_events_module')
    op.drop_column('data_block', 'count_events_finalization')
    op.drop_column('data_block', 'count_events_extrinsic')
    op.drop_column('data_block', 'count_accounts_new')
    op.drop_column('data_block', 'blocktime')
    op.drop_index(op.f('ix_runtime_storage_lookup'), table_name='runtime_storage')
    op.drop_table('runtime_storage')
    # ### end Alembic commands ###
