"""Added count_constants count_errors fields

Revision ID: 0b385b73588e
Revises: b7aade4297e6
Create Date: 2019-11-14 18:42:31.764069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b385b73588e'
down_revision = 'b7aade4297e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtime_module', sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False))
    op.add_column('runtime_module', sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtime_module', 'count_errors')
    op.drop_column('runtime_module', 'count_constants')
    # ### end Alembic commands ###
