"""Add account id to council motion

Revision ID: 0e1658a7de2a
Revises: da691ae8609a
Create Date: 2019-12-10 18:57:03.417449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1658a7de2a'
down_revision = 'da691ae8609a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_council_motion', sa.Column('account_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_council_motion', 'account_id')
    # ### end Alembic commands ###
