"""Added runtime constant table

Revision ID: 1115d9423904
Revises: fea3e3c2e1d3
Create Date: 2019-07-15 14:32:24.076546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1115d9423904'
down_revision = 'fea3e3c2e1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_constant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_constant_name'), 'runtime_constant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_constant_name'), table_name='runtime_constant')
    op.drop_table('runtime_constant')
    # ### end Alembic commands ###
