"""Validator changes

Revision ID: 195a4677ffd5
Revises: 1e6da577c3aa
Create Date: 2019-07-31 11:25:31.882494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '195a4677ffd5'
down_revision = '1e6da577c3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_session_nominator_nominator', table_name='data_session_nominator')
    op.drop_index('ix_data_session_nominator_validator', table_name='data_session_nominator')
    op.drop_table('data_session_nominator')
    op.add_column('data_session_validator', sa.Column('bonded_active', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('bonded_nominators', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('bonded_own', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('bonded_total', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('unlocking', sa.JSON(), nullable=True))
    op.add_column('data_session_validator', sa.Column('validator_controller', sa.String(length=64), nullable=True))
    op.add_column('data_session_validator', sa.Column('validator_session', sa.String(length=64), nullable=True))
    op.add_column('data_session_validator', sa.Column('validator_stash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_session_validator_rank_validator'), 'data_session_validator', ['rank_validator'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_controller'), 'data_session_validator', ['validator_controller'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_session'), 'data_session_validator', ['validator_session'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_stash'), 'data_session_validator', ['validator_stash'], unique=False)
    op.drop_index('ix_data_session_validator_validator', table_name='data_session_validator')
    op.drop_column('data_session_validator', 'validator')

    op.drop_constraint('PRIMARY', 'data_session_validator', type_='primary')
    op.create_primary_key("data_session_validator_pk", "data_session_validator",
                          ["session_id", "rank_validator"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_session_validator', sa.Column('validator', mysql.VARCHAR(length=64), nullable=False))
    op.create_index('ix_data_session_validator_validator', 'data_session_validator', ['validator'], unique=False)
    op.drop_index(op.f('ix_data_session_validator_validator_stash'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_validator_session'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_validator_controller'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_rank_validator'), table_name='data_session_validator')
    op.drop_column('data_session_validator', 'validator_stash')
    op.drop_column('data_session_validator', 'validator_session')
    op.drop_column('data_session_validator', 'validator_controller')
    op.drop_column('data_session_validator', 'unlocking')
    op.drop_column('data_session_validator', 'bonded_total')
    op.drop_column('data_session_validator', 'bonded_own')
    op.drop_column('data_session_validator', 'bonded_nominators')
    op.drop_column('data_session_validator', 'bonded_active')
    op.create_table('data_session_nominator',
    sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('validator', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('nominator', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'validator', 'nominator'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_data_session_nominator_validator', 'data_session_nominator', ['validator'], unique=False)
    op.create_index('ix_data_session_nominator_nominator', 'data_session_nominator', ['nominator'], unique=False)
    # ### end Alembic commands ###
