"""Added indices on log table

Revision ID: 21fd70e7cbf6
Revises: 1115d9423904
Create Date: 2019-07-16 18:10:41.594443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fd70e7cbf6'
down_revision = '1115d9423904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_log_block_id'), 'data_log', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_log_log_idx'), 'data_log', ['log_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_log_log_idx'), table_name='data_log')
    op.drop_index(op.f('ix_data_log_block_id'), table_name='data_log')
    # ### end Alembic commands ###
