"""Initial db layout

Revision ID: 38a7f29de7c7
Revises: 
Create Date: 2020-04-16 12:51:44.832584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38a7f29de7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_account',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=48), nullable=True),
    sa.Column('index_address', sa.String(length=24), nullable=True),
    sa.Column('is_reaped', sa.Boolean(), nullable=True),
    sa.Column('is_validator', sa.Boolean(), nullable=True),
    sa.Column('was_validator', sa.Boolean(), nullable=True),
    sa.Column('is_nominator', sa.Boolean(), nullable=True),
    sa.Column('was_nominator', sa.Boolean(), nullable=True),
    sa.Column('is_council_member', sa.Boolean(), nullable=True),
    sa.Column('was_council_member', sa.Boolean(), nullable=True),
    sa.Column('is_tech_comm_member', sa.Boolean(), nullable=True),
    sa.Column('was_tech_comm_member', sa.Boolean(), nullable=True),
    sa.Column('is_registrar', sa.Boolean(), nullable=True),
    sa.Column('was_registrar', sa.Boolean(), nullable=True),
    sa.Column('is_sudo', sa.Boolean(), nullable=True),
    sa.Column('was_sudo', sa.Boolean(), nullable=True),
    sa.Column('is_treasury', sa.Boolean(), nullable=True),
    sa.Column('is_contract', sa.Boolean(), nullable=True),
    sa.Column('count_reaped', sa.Integer(), nullable=True),
    sa.Column('hash_blake2b', sa.String(length=64), nullable=True),
    sa.Column('balance_total', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('balance_free', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('balance_reserved', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('account_info', sa.JSON(), nullable=True),
    sa.Column('has_identity', sa.Boolean(), nullable=True),
    sa.Column('has_subidentity', sa.Boolean(), nullable=True),
    sa.Column('identity_display', sa.String(length=32), nullable=True),
    sa.Column('identity_legal', sa.String(length=32), nullable=True),
    sa.Column('identity_web', sa.String(length=32), nullable=True),
    sa.Column('identity_riot', sa.String(length=32), nullable=True),
    sa.Column('identity_email', sa.String(length=32), nullable=True),
    sa.Column('identity_twitter', sa.String(length=32), nullable=True),
    sa.Column('identity_judgement_good', sa.Integer(), nullable=True),
    sa.Column('identity_judgement_bad', sa.Integer(), nullable=True),
    sa.Column('parent_identity', sa.String(length=64), nullable=True),
    sa.Column('subidentity_display', sa.String(length=32), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_address'), 'data_account', ['address'], unique=False)
    op.create_index(op.f('ix_data_account_balance_free'), 'data_account', ['balance_free'], unique=False)
    op.create_index(op.f('ix_data_account_balance_reserved'), 'data_account', ['balance_reserved'], unique=False)
    op.create_index(op.f('ix_data_account_balance_total'), 'data_account', ['balance_total'], unique=False)
    op.create_index(op.f('ix_data_account_has_identity'), 'data_account', ['has_identity'], unique=False)
    op.create_index(op.f('ix_data_account_has_subidentity'), 'data_account', ['has_subidentity'], unique=False)
    op.create_index(op.f('ix_data_account_hash_blake2b'), 'data_account', ['hash_blake2b'], unique=False)
    op.create_index(op.f('ix_data_account_identity_display'), 'data_account', ['identity_display'], unique=False)
    op.create_index(op.f('ix_data_account_index_address'), 'data_account', ['index_address'], unique=False)
    op.create_index(op.f('ix_data_account_is_contract'), 'data_account', ['is_contract'], unique=False)
    op.create_index(op.f('ix_data_account_is_council_member'), 'data_account', ['is_council_member'], unique=False)
    op.create_index(op.f('ix_data_account_is_nominator'), 'data_account', ['is_nominator'], unique=False)
    op.create_index(op.f('ix_data_account_is_registrar'), 'data_account', ['is_registrar'], unique=False)
    op.create_index(op.f('ix_data_account_is_sudo'), 'data_account', ['is_sudo'], unique=False)
    op.create_index(op.f('ix_data_account_is_tech_comm_member'), 'data_account', ['is_tech_comm_member'], unique=False)
    op.create_index(op.f('ix_data_account_is_treasury'), 'data_account', ['is_treasury'], unique=False)
    op.create_index(op.f('ix_data_account_is_validator'), 'data_account', ['is_validator'], unique=False)
    op.create_index(op.f('ix_data_account_parent_identity'), 'data_account', ['parent_identity'], unique=False)
    op.create_index(op.f('ix_data_account_was_council_member'), 'data_account', ['was_council_member'], unique=False)
    op.create_index(op.f('ix_data_account_was_nominator'), 'data_account', ['was_nominator'], unique=False)
    op.create_index(op.f('ix_data_account_was_registrar'), 'data_account', ['was_registrar'], unique=False)
    op.create_index(op.f('ix_data_account_was_sudo'), 'data_account', ['was_sudo'], unique=False)
    op.create_index(op.f('ix_data_account_was_tech_comm_member'), 'data_account', ['was_tech_comm_member'], unique=False)
    op.create_index(op.f('ix_data_account_was_validator'), 'data_account', ['was_validator'], unique=False)
    op.create_table('data_account_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_audit_block_id'), 'data_account_audit', ['block_id'], unique=False)
    op.create_table('data_account_index',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('short_address', sa.String(length=24), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('is_reclaimable', sa.Boolean(), nullable=True),
    sa.Column('is_reclaimed', sa.Boolean(), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_index_account_id'), 'data_account_index', ['account_id'], unique=False)
    op.create_index(op.f('ix_data_account_index_short_address'), 'data_account_index', ['short_address'], unique=False)
    op.create_table('data_account_index_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_index_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_index_audit_account_id'), 'data_account_index_audit', ['account_id'], unique=False)
    op.create_index(op.f('ix_data_account_index_audit_account_index_id'), 'data_account_index_audit', ['account_index_id'], unique=False)
    op.create_index(op.f('ix_data_account_index_audit_block_id'), 'data_account_index_audit', ['block_id'], unique=False)
    op.create_table('data_account_info_snapshot',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('balance_total', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('balance_free', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('balance_reserved', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('account_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'account_id')
    )
    op.create_index(op.f('ix_data_account_info_snapshot_account_id'), 'data_account_info_snapshot', ['account_id'], unique=False)
    op.create_index(op.f('ix_data_account_info_snapshot_balance_free'), 'data_account_info_snapshot', ['balance_free'], unique=False)
    op.create_index(op.f('ix_data_account_info_snapshot_balance_reserved'), 'data_account_info_snapshot', ['balance_reserved'], unique=False)
    op.create_index(op.f('ix_data_account_info_snapshot_balance_total'), 'data_account_info_snapshot', ['balance_total'], unique=False)
    op.create_index(op.f('ix_data_account_info_snapshot_block_id'), 'data_account_info_snapshot', ['block_id'], unique=False)
    op.create_table('data_account_search_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('index_type_id', sa.Integer(), nullable=False),
    sa.Column('sorting_value', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_search_index_account_id'), 'data_account_search_index', ['account_id'], unique=False)
    op.create_index(op.f('ix_data_account_search_index_block_id'), 'data_account_search_index', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_account_search_index_event_idx'), 'data_account_search_index', ['event_idx'], unique=False)
    op.create_index(op.f('ix_data_account_search_index_extrinsic_idx'), 'data_account_search_index', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_account_search_index_index_type_id'), 'data_account_search_index', ['index_type_id'], unique=False)
    op.create_index(op.f('ix_data_account_search_index_sorting_value'), 'data_account_search_index', ['sorting_value'], unique=False)
    op.create_table('data_account_search_index_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_search_index_type_name'), 'data_account_search_index_type', ['name'], unique=False)
    op.create_table('data_block',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('state_root', sa.String(length=66), nullable=False),
    sa.Column('extrinsics_root', sa.String(length=66), nullable=False),
    sa.Column('count_extrinsics', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_unsigned', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signed', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_error', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_success', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signedby_address', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signedby_index', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_events_system', sa.Integer(), nullable=False),
    sa.Column('count_events_module', sa.Integer(), nullable=False),
    sa.Column('count_events_extrinsic', sa.Integer(), nullable=False),
    sa.Column('count_events_finalization', sa.Integer(), nullable=False),
    sa.Column('count_accounts', sa.Integer(), nullable=False),
    sa.Column('count_accounts_new', sa.Integer(), nullable=False),
    sa.Column('count_accounts_reaped', sa.Integer(), nullable=False),
    sa.Column('count_sessions_new', sa.Integer(), nullable=False),
    sa.Column('count_contracts_new', sa.Integer(), nullable=False),
    sa.Column('count_log', sa.Integer(), nullable=False),
    sa.Column('range10000', sa.Integer(), nullable=False),
    sa.Column('range100000', sa.Integer(), nullable=False),
    sa.Column('range1000000', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('full_month', sa.Integer(), nullable=True),
    sa.Column('full_week', sa.Integer(), nullable=True),
    sa.Column('full_day', sa.Integer(), nullable=True),
    sa.Column('full_hour', sa.Integer(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('authority_index', sa.Integer(), nullable=True),
    sa.Column('slot_number', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('spec_version_id', sa.String(length=64), nullable=False),
    sa.Column('debug_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_block_hash'), 'data_block', ['hash'], unique=True)
    op.create_index(op.f('ix_data_block_parent_hash'), 'data_block', ['parent_hash'], unique=False)
    op.create_table('data_block_total',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('parent_datetime', sa.DateTime(), nullable=True),
    sa.Column('blocktime', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('total_extrinsics', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_success', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_error', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_signed', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_unsigned', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_signedby_address', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_signedby_index', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_system', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_module', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_extrinsic', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_finalization', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_logs', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_blocktime', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_accounts', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_accounts_new', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_accounts_reaped', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_sessions_new', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_contracts_new', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_block_total_author'), 'data_block_total', ['author'], unique=False)
    op.create_table('data_contract',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('bytecode', mysql.LONGTEXT(), nullable=True),
    sa.Column('source', mysql.LONGTEXT(), nullable=True),
    sa.Column('abi', sa.JSON(), nullable=True),
    sa.Column('compiler', sa.String(length=64), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_table('data_event',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('system', sa.SmallInteger(), nullable=False),
    sa.Column('module', sa.SmallInteger(), nullable=False),
    sa.Column('phase', sa.SmallInteger(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'event_idx')
    )
    op.create_index(op.f('ix_data_event_block_id'), 'data_event', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_event_event_id'), 'data_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_data_event_event_idx'), 'data_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_data_event_extrinsic_idx'), 'data_event', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_event_module'), 'data_event', ['module'], unique=False)
    op.create_index(op.f('ix_data_event_module_id'), 'data_event', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_event_system'), 'data_event', ['system'], unique=False)
    op.create_index(op.f('ix_data_event_type'), 'data_event', ['type'], unique=False)
    op.create_table('data_extrinsic',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_hash', sa.String(length=64), nullable=True),
    sa.Column('extrinsic_length', sa.String(length=10), nullable=True),
    sa.Column('extrinsic_version', sa.String(length=2), nullable=True),
    sa.Column('signed', sa.SmallInteger(), nullable=False),
    sa.Column('unsigned', sa.SmallInteger(), nullable=False),
    sa.Column('signedby_address', sa.SmallInteger(), nullable=False),
    sa.Column('signedby_index', sa.SmallInteger(), nullable=False),
    sa.Column('address_length', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('account_index', sa.String(length=16), nullable=True),
    sa.Column('account_idx', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=4), nullable=True),
    sa.Column('call', sa.String(length=4), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.SmallInteger(), nullable=False),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_data_extrinsic_account_idx'), 'data_extrinsic', ['account_idx'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_account_index'), 'data_extrinsic', ['account_index'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_address'), 'data_extrinsic', ['address'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_block_id'), 'data_extrinsic', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_call_id'), 'data_extrinsic', ['call_id'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_extrinsic_hash'), 'data_extrinsic', ['extrinsic_hash'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_extrinsic_idx'), 'data_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_module_id'), 'data_extrinsic', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_signed'), 'data_extrinsic', ['signed'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_unsigned'), 'data_extrinsic', ['unsigned'], unique=False)
    op.create_table('data_identity_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_identity_audit_block_id'), 'data_identity_audit', ['block_id'], unique=False)
    op.create_table('data_identity_judgement',
    sa.Column('registrar_index', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('judgement', sa.String(length=32), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('registrar_index', 'account_id')
    )
    op.create_index(op.f('ix_data_identity_judgement_account_id'), 'data_identity_judgement', ['account_id'], unique=False)
    op.create_table('data_identity_judgement_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registrar_index', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_identity_judgement_audit_block_id'), 'data_identity_judgement_audit', ['block_id'], unique=False)
    op.create_table('data_log',
    sa.Column('block_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('log_idx', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'log_idx')
    )
    op.create_index(op.f('ix_data_log_type_id'), 'data_log', ['type_id'], unique=False)
    op.create_table('data_reorg_block',
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('state_root', sa.String(length=66), nullable=False),
    sa.Column('extrinsics_root', sa.String(length=66), nullable=False),
    sa.Column('count_extrinsics', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_unsigned', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signed', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_error', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_success', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signedby_address', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signedby_index', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_events_system', sa.Integer(), nullable=False),
    sa.Column('count_events_module', sa.Integer(), nullable=False),
    sa.Column('count_events_extrinsic', sa.Integer(), nullable=False),
    sa.Column('count_events_finalization', sa.Integer(), nullable=False),
    sa.Column('count_accounts', sa.Integer(), nullable=False),
    sa.Column('count_accounts_new', sa.Integer(), nullable=False),
    sa.Column('count_accounts_reaped', sa.Integer(), nullable=False),
    sa.Column('count_sessions_new', sa.Integer(), nullable=False),
    sa.Column('count_contracts_new', sa.Integer(), nullable=False),
    sa.Column('count_log', sa.Integer(), nullable=False),
    sa.Column('range10000', sa.Integer(), nullable=False),
    sa.Column('range100000', sa.Integer(), nullable=False),
    sa.Column('range1000000', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('full_month', sa.Integer(), nullable=True),
    sa.Column('full_week', sa.Integer(), nullable=True),
    sa.Column('full_day', sa.Integer(), nullable=True),
    sa.Column('full_hour', sa.Integer(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('authority_index', sa.Integer(), nullable=True),
    sa.Column('slot_number', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('spec_version_id', sa.String(length=64), nullable=False),
    sa.Column('debug_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_data_reorg_block_hash'), 'data_reorg_block', ['hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_block_id'), 'data_reorg_block', ['id'], unique=False)
    op.create_index(op.f('ix_data_reorg_block_parent_hash'), 'data_reorg_block', ['parent_hash'], unique=False)
    op.create_table('data_reorg_event',
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('system', sa.SmallInteger(), nullable=False),
    sa.Column('module', sa.SmallInteger(), nullable=False),
    sa.Column('phase', sa.SmallInteger(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'event_idx')
    )
    op.create_index(op.f('ix_data_reorg_event_block_hash'), 'data_reorg_event', ['block_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_block_id'), 'data_reorg_event', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_event_id'), 'data_reorg_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_event_idx'), 'data_reorg_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_extrinsic_idx'), 'data_reorg_event', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_module'), 'data_reorg_event', ['module'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_module_id'), 'data_reorg_event', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_system'), 'data_reorg_event', ['system'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_type'), 'data_reorg_event', ['type'], unique=False)
    op.create_table('data_reorg_extrinsic',
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_hash', sa.String(length=64), nullable=True),
    sa.Column('extrinsic_length', sa.String(length=10), nullable=True),
    sa.Column('extrinsic_version', sa.String(length=2), nullable=True),
    sa.Column('signed', sa.SmallInteger(), nullable=False),
    sa.Column('unsigned', sa.SmallInteger(), nullable=False),
    sa.Column('signedby_address', sa.SmallInteger(), nullable=False),
    sa.Column('signedby_index', sa.SmallInteger(), nullable=False),
    sa.Column('address_length', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('account_index', sa.String(length=16), nullable=True),
    sa.Column('account_idx', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=4), nullable=True),
    sa.Column('call', sa.String(length=4), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.SmallInteger(), nullable=False),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_data_reorg_extrinsic_account_idx'), 'data_reorg_extrinsic', ['account_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_account_index'), 'data_reorg_extrinsic', ['account_index'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_address'), 'data_reorg_extrinsic', ['address'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_block_hash'), 'data_reorg_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_block_id'), 'data_reorg_extrinsic', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_call_id'), 'data_reorg_extrinsic', ['call_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_extrinsic_hash'), 'data_reorg_extrinsic', ['extrinsic_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_extrinsic_idx'), 'data_reorg_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_module_id'), 'data_reorg_extrinsic', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_signed'), 'data_reorg_extrinsic', ['signed'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_unsigned'), 'data_reorg_extrinsic', ['unsigned'], unique=False)
    op.create_table('data_reorg_log',
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('log_idx', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'log_idx')
    )
    op.create_index(op.f('ix_data_reorg_log_block_hash'), 'data_reorg_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_log_type_id'), 'data_reorg_log', ['type_id'], unique=False)
    op.create_table('data_session',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('start_at_block', sa.Integer(), nullable=True),
    sa.Column('era', sa.Integer(), nullable=True),
    sa.Column('era_idx', sa.Integer(), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.Column('count_validators', sa.Integer(), nullable=True),
    sa.Column('count_nominators', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_session_nominator',
    sa.Column('session_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('rank_validator', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('rank_nominator', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nominator_stash', sa.String(length=64), nullable=True),
    sa.Column('nominator_controller', sa.String(length=64), nullable=True),
    sa.Column('bonded', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'rank_validator', 'rank_nominator')
    )
    op.create_index(op.f('ix_data_session_nominator_nominator_controller'), 'data_session_nominator', ['nominator_controller'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_nominator_stash'), 'data_session_nominator', ['nominator_stash'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_rank_nominator'), 'data_session_nominator', ['rank_nominator'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_rank_validator'), 'data_session_nominator', ['rank_validator'], unique=False)
    op.create_table('data_session_total',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('end_at_block', sa.Integer(), nullable=True),
    sa.Column('count_blocks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_session_validator',
    sa.Column('session_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('rank_validator', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('validator_stash', sa.String(length=64), nullable=True),
    sa.Column('validator_controller', sa.String(length=64), nullable=True),
    sa.Column('validator_session', sa.String(length=64), nullable=True),
    sa.Column('bonded_total', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('bonded_active', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('bonded_nominators', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('bonded_own', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('unlocking', sa.JSON(), nullable=True),
    sa.Column('count_nominators', sa.Integer(), nullable=True),
    sa.Column('unstake_threshold', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'rank_validator')
    )
    op.create_index(op.f('ix_data_session_validator_rank_validator'), 'data_session_validator', ['rank_validator'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_controller'), 'data_session_validator', ['validator_controller'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_session'), 'data_session_validator', ['validator_session'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_stash'), 'data_session_validator', ['validator_stash'], unique=False)
    op.create_table('data_storage',
    sa.Column('block_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('storage_key_prefix', sa.String(length=64), nullable=True),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('module_prefix', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('return_type', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('data_raw', mysql.LONGTEXT(), nullable=True),
    sa.Column('error', sa.SmallInteger(), nullable=False),
    sa.Column('comments', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'storage_key')
    )
    op.create_index(op.f('ix_data_storage_block_id'), 'data_storage', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_storage_spec_version_id'), 'data_storage', ['spec_version_id'], unique=False)
    op.create_index(op.f('ix_data_storage_storage_key'), 'data_storage', ['storage_key'], unique=False)
    op.create_index(op.f('ix_data_storage_storage_key_prefix'), 'data_storage', ['storage_key_prefix'], unique=False)
    op.create_table('harvester_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('harvester_status',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('runtime',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('impl_name', sa.String(length=255), nullable=True),
    sa.Column('impl_version', sa.Integer(), nullable=True),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('spec_name', sa.String(length=255), nullable=True),
    sa.Column('authoring_version', sa.Integer(), nullable=True),
    sa.Column('apis', sa.JSON(), nullable=True),
    sa.Column('json_metadata', sa.JSON(), nullable=True),
    sa.Column('json_metadata_decoded', sa.JSON(), nullable=True),
    sa.Column('count_modules', sa.Integer(), nullable=False),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version')
    )
    op.create_table('runtime_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_params', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'module_id', 'call_id')
    )
    op.create_index(op.f('ix_runtime_call_lookup'), 'runtime_call', ['lookup'], unique=False)
    op.create_table('runtime_call_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_call_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_call_id', 'name')
    )
    op.create_table('runtime_constant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_constant_name'), 'runtime_constant', ['name'], unique=False)
    op.create_table('runtime_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_error_name'), 'runtime_error', ['name'], unique=False)
    op.create_table('runtime_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_attributes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'module_id', 'event_id')
    )
    op.create_index(op.f('ix_runtime_event_lookup'), 'runtime_event', ['lookup'], unique=False)
    op.create_table('runtime_event_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_event_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_event_id', 'index')
    )
    op.create_table('runtime_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_constants', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_errors', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'module_id')
    )
    op.create_index(op.f('ix_runtime_module_lookup'), 'runtime_module', ['lookup'], unique=False)
    op.create_table('runtime_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('default', sa.String(length=255), nullable=True),
    sa.Column('modifier', sa.String(length=64), nullable=True),
    sa.Column('type_hasher', sa.String(length=255), nullable=True),
    sa.Column('type_key1', sa.String(length=255), nullable=True),
    sa.Column('type_key2', sa.String(length=255), nullable=True),
    sa.Column('type_value', sa.String(length=255), nullable=True),
    sa.Column('type_is_linked', sa.SmallInteger(), nullable=True),
    sa.Column('type_key2hasher', sa.String(length=255), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_storage_lookup'), 'runtime_storage', ['lookup'], unique=False)
    op.create_table('runtime_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('type_string', sa.String(length=255), nullable=True),
    sa.Column('decoder_class', sa.String(length=255), nullable=True),
    sa.Column('is_primitive_runtime', sa.Boolean(), nullable=True),
    sa.Column('is_primitive_core', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'type_string')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_type')
    op.drop_index(op.f('ix_runtime_storage_lookup'), table_name='runtime_storage')
    op.drop_table('runtime_storage')
    op.drop_index(op.f('ix_runtime_module_lookup'), table_name='runtime_module')
    op.drop_table('runtime_module')
    op.drop_table('runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_lookup'), table_name='runtime_event')
    op.drop_table('runtime_event')
    op.drop_index(op.f('ix_runtime_error_name'), table_name='runtime_error')
    op.drop_table('runtime_error')
    op.drop_index(op.f('ix_runtime_constant_name'), table_name='runtime_constant')
    op.drop_table('runtime_constant')
    op.drop_table('runtime_call_param')
    op.drop_index(op.f('ix_runtime_call_lookup'), table_name='runtime_call')
    op.drop_table('runtime_call')
    op.drop_table('runtime')
    op.drop_table('harvester_status')
    op.drop_table('harvester_setting')
    op.drop_index(op.f('ix_data_storage_storage_key_prefix'), table_name='data_storage')
    op.drop_index(op.f('ix_data_storage_storage_key'), table_name='data_storage')
    op.drop_index(op.f('ix_data_storage_spec_version_id'), table_name='data_storage')
    op.drop_index(op.f('ix_data_storage_block_id'), table_name='data_storage')
    op.drop_table('data_storage')
    op.drop_index(op.f('ix_data_session_validator_validator_stash'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_validator_session'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_validator_controller'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_rank_validator'), table_name='data_session_validator')
    op.drop_table('data_session_validator')
    op.drop_table('data_session_total')
    op.drop_index(op.f('ix_data_session_nominator_rank_validator'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_rank_nominator'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_nominator_stash'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_nominator_controller'), table_name='data_session_nominator')
    op.drop_table('data_session_nominator')
    op.drop_table('data_session')
    op.drop_index(op.f('ix_data_reorg_log_type_id'), table_name='data_reorg_log')
    op.drop_index(op.f('ix_data_reorg_log_block_hash'), table_name='data_reorg_log')
    op.drop_table('data_reorg_log')
    op.drop_index(op.f('ix_data_reorg_extrinsic_unsigned'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_signed'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_module_id'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_extrinsic_idx'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_extrinsic_hash'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_call_id'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_block_id'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_block_hash'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_address'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_account_index'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_account_idx'), table_name='data_reorg_extrinsic')
    op.drop_table('data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_event_type'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_system'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_module_id'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_module'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_extrinsic_idx'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_event_idx'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_event_id'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_block_id'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_block_hash'), table_name='data_reorg_event')
    op.drop_table('data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_block_parent_hash'), table_name='data_reorg_block')
    op.drop_index(op.f('ix_data_reorg_block_id'), table_name='data_reorg_block')
    op.drop_index(op.f('ix_data_reorg_block_hash'), table_name='data_reorg_block')
    op.drop_table('data_reorg_block')
    op.drop_index(op.f('ix_data_log_type_id'), table_name='data_log')
    op.drop_table('data_log')
    op.drop_index(op.f('ix_data_identity_judgement_audit_block_id'), table_name='data_identity_judgement_audit')
    op.drop_table('data_identity_judgement_audit')
    op.drop_index(op.f('ix_data_identity_judgement_account_id'), table_name='data_identity_judgement')
    op.drop_table('data_identity_judgement')
    op.drop_index(op.f('ix_data_identity_audit_block_id'), table_name='data_identity_audit')
    op.drop_table('data_identity_audit')
    op.drop_index(op.f('ix_data_extrinsic_unsigned'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_signed'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_module_id'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_extrinsic_idx'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_extrinsic_hash'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_call_id'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_block_id'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_address'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_account_index'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_account_idx'), table_name='data_extrinsic')
    op.drop_table('data_extrinsic')
    op.drop_index(op.f('ix_data_event_type'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_system'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_module_id'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_module'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_extrinsic_idx'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_event_idx'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_event_id'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_block_id'), table_name='data_event')
    op.drop_table('data_event')
    op.drop_table('data_contract')
    op.drop_index(op.f('ix_data_block_total_author'), table_name='data_block_total')
    op.drop_table('data_block_total')
    op.drop_index(op.f('ix_data_block_parent_hash'), table_name='data_block')
    op.drop_index(op.f('ix_data_block_hash'), table_name='data_block')
    op.drop_table('data_block')
    op.drop_index(op.f('ix_data_account_search_index_type_name'), table_name='data_account_search_index_type')
    op.drop_table('data_account_search_index_type')
    op.drop_index(op.f('ix_data_account_search_index_sorting_value'), table_name='data_account_search_index')
    op.drop_index(op.f('ix_data_account_search_index_index_type_id'), table_name='data_account_search_index')
    op.drop_index(op.f('ix_data_account_search_index_extrinsic_idx'), table_name='data_account_search_index')
    op.drop_index(op.f('ix_data_account_search_index_event_idx'), table_name='data_account_search_index')
    op.drop_index(op.f('ix_data_account_search_index_block_id'), table_name='data_account_search_index')
    op.drop_index(op.f('ix_data_account_search_index_account_id'), table_name='data_account_search_index')
    op.drop_table('data_account_search_index')
    op.drop_index(op.f('ix_data_account_info_snapshot_block_id'), table_name='data_account_info_snapshot')
    op.drop_index(op.f('ix_data_account_info_snapshot_balance_total'), table_name='data_account_info_snapshot')
    op.drop_index(op.f('ix_data_account_info_snapshot_balance_reserved'), table_name='data_account_info_snapshot')
    op.drop_index(op.f('ix_data_account_info_snapshot_balance_free'), table_name='data_account_info_snapshot')
    op.drop_index(op.f('ix_data_account_info_snapshot_account_id'), table_name='data_account_info_snapshot')
    op.drop_table('data_account_info_snapshot')
    op.drop_index(op.f('ix_data_account_index_audit_block_id'), table_name='data_account_index_audit')
    op.drop_index(op.f('ix_data_account_index_audit_account_index_id'), table_name='data_account_index_audit')
    op.drop_index(op.f('ix_data_account_index_audit_account_id'), table_name='data_account_index_audit')
    op.drop_table('data_account_index_audit')
    op.drop_index(op.f('ix_data_account_index_short_address'), table_name='data_account_index')
    op.drop_index(op.f('ix_data_account_index_account_id'), table_name='data_account_index')
    op.drop_table('data_account_index')
    op.drop_index(op.f('ix_data_account_audit_block_id'), table_name='data_account_audit')
    op.drop_table('data_account_audit')
    op.drop_index(op.f('ix_data_account_was_validator'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_was_tech_comm_member'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_was_sudo'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_was_registrar'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_was_nominator'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_was_council_member'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_parent_identity'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_validator'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_treasury'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_tech_comm_member'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_sudo'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_registrar'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_nominator'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_council_member'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_is_contract'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_index_address'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_identity_display'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_hash_blake2b'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_has_subidentity'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_has_identity'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_balance_total'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_balance_reserved'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_balance_free'), table_name='data_account')
    op.drop_index(op.f('ix_data_account_address'), table_name='data_account')
    op.drop_table('data_account')
    # ### end Alembic commands ###
