"""Added runtime tables

Revision ID: 67a2febe1793
Revises: fed48c78b8b6
Create Date: 2019-04-17 16:57:40.369180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a2febe1793'
down_revision = 'fed48c78b8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_string', sa.String(length=255), nullable=True),
    sa.Column('mapped_type_string', sa.String(length=255), nullable=True),
    sa.Column('decoder_class', sa.String(length=255), nullable=True),
    sa.Column('created_at_runtime_id', sa.Integer(), nullable=True),
    sa.Column('updated_at_runtime_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_string')
    )
    op.create_table('runtime',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('impl_name', sa.String(length=255), nullable=True),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runtime_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_params', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'module_id', 'call_id')
    )
    op.create_index(op.f('ix_runtime_call_lookup'), 'runtime_call', ['lookup'], unique=False)
    op.create_table('runtime_call_param',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_call_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_call_id', 'name')
    )
    op.create_table('runtime_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('count_attributes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'module_id', 'event_id')
    )
    op.create_index(op.f('ix_runtime_event_lookup'), 'runtime_event', ['lookup'], unique=False)
    op.create_table('runtime_event_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_event_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_event_id', 'index')
    )
    op.create_table('runtime_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lookup', sa.String(length=4), nullable=True),
    sa.Column('count_call_functions', sa.Integer(), nullable=False),
    sa.Column('count_storage_functions', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'module_id')
    )
    op.create_index(op.f('ix_runtime_module_lookup'), 'runtime_module', ['lookup'], unique=False)
    op.add_column('metadata', sa.Column('count_call_functions', sa.Integer(), nullable=False))
    op.add_column('metadata', sa.Column('count_events', sa.Integer(), nullable=False))
    op.add_column('metadata', sa.Column('count_modules', sa.Integer(), nullable=False))
    op.add_column('metadata', sa.Column('count_storage_functions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metadata', 'count_storage_functions')
    op.drop_column('metadata', 'count_modules')
    op.drop_column('metadata', 'count_events')
    op.drop_column('metadata', 'count_call_functions')
    op.drop_index(op.f('ix_runtime_module_lookup'), table_name='runtime_module')
    op.drop_table('runtime_module')
    op.drop_table('runtime_event_attribute')
    op.drop_index(op.f('ix_runtime_event_lookup'), table_name='runtime_event')
    op.drop_table('runtime_event')
    op.drop_table('runtime_call_param')
    op.drop_index(op.f('ix_runtime_call_lookup'), table_name='runtime_call')
    op.drop_table('runtime_call')
    op.drop_table('runtime')
    op.drop_table('metadata_type')
    # ### end Alembic commands ###
