"""Session total table

Revision ID: 74463478f3e4
Revises: 904e857e3170
Create Date: 2019-06-26 12:36:29.608118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74463478f3e4'
down_revision = '904e857e3170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_session_total',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('end_at_block', sa.Integer(), nullable=True),
    sa.Column('count_blocks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('data_session', 'end_at_block')
    op.drop_column('data_session', 'count_blocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_session', sa.Column('count_blocks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data_session', sa.Column('end_at_block', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('data_session_total')
    # ### end Alembic commands ###
