"""Added data_block_total table

Revision ID: 7a876737373d
Revises: eb9113e36e1e
Create Date: 2019-06-18 18:22:44.839540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a876737373d'
down_revision = 'eb9113e36e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_block_total',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('parent_datetime', sa.DateTime(), nullable=True),
    sa.Column('blocktime', sa.Integer(), nullable=False),
    sa.Column('total_extrinsics', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_success', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_error', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_signed', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_unsigned', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_signedby_address', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_extrinsics_signedby_index', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_system', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_module', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_extrinsic', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_events_finalization', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_logs', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_blocktime', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_accounts', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_accounts_new', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_accounts_reaped', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_sessions_new', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('total_contracts_new', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_block.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('data_block', 'blocktime')
    op.drop_column('data_block', 'parent_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_block', sa.Column('parent_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('data_block', sa.Column('blocktime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('data_block_total')
    # ### end Alembic commands ###
