"""Session validator nominator

Revision ID: 7d3a5a5ef6c2
Revises: 74463478f3e4
Create Date: 2019-06-28 11:16:31.161949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3a5a5ef6c2'
down_revision = '74463478f3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_session_nominator',
    sa.Column('session_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('validator', sa.String(length=64), nullable=False),
    sa.Column('nominator', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('session_id', 'validator', 'nominator')
    )
    op.create_index(op.f('ix_data_session_nominator_nominator'), 'data_session_nominator', ['nominator'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_validator'), 'data_session_nominator', ['validator'], unique=False)
    op.create_table('data_session_validator',
    sa.Column('session_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('validator', sa.String(length=64), nullable=False),
    sa.Column('rank_validator', sa.Integer(), nullable=True),
    sa.Column('count_nominators', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('session_id', 'validator')
    )
    op.create_index(op.f('ix_data_session_validator_validator'), 'data_session_validator', ['validator'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_session_validator_validator'), table_name='data_session_validator')
    op.drop_table('data_session_validator')
    op.drop_index(op.f('ix_data_session_nominator_validator'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_nominator'), table_name='data_session_nominator')
    op.drop_table('data_session_nominator')
    # ### end Alembic commands ###
