"""Added impl_version

Revision ID: 7fbc3f613fa9
Revises: ba1bdb560610
Create Date: 2019-06-05 16:50:31.569575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fbc3f613fa9'
down_revision = 'ba1bdb560610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_block', 'full_week')
    op.drop_column('data_block', 'full_day')
    op.drop_column('data_block', 'full_hour')
    op.drop_column('data_block', 'full_month')
    op.add_column('runtime', sa.Column('impl_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtime', 'impl_version')
    op.add_column('data_block', sa.Column('full_month', mysql.VARCHAR(length=7), nullable=True))
    op.add_column('data_block', sa.Column('full_hour', mysql.VARCHAR(length=13), nullable=True))
    op.add_column('data_block', sa.Column('full_day', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('data_block', sa.Column('full_week', mysql.VARCHAR(length=7), nullable=True))
    # ### end Alembic commands ###
