"""Add asset balances

Revision ID: 859005ea8024
Revises: 9975e95a749c
Create Date: 2021-07-13 07:13:03.031230

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "859005ea8024"
down_revision = "9975e95a749c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_asset_balance",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("balance_free", sa.Numeric(precision=65, scale=0), nullable=False),
        sa.Column("balance_frozen", sa.Numeric(precision=65, scale=0), nullable=False),
        sa.Column(
            "balance_reserved", sa.Numeric(precision=65, scale=0), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["data_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["data_asset.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "account_id"),
        sa.UniqueConstraint("asset_id", "account_id"),
    )
    op.create_index(
        op.f("ix_data_asset_balance_balance_free"),
        "data_asset_balance",
        ["balance_free"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_asset_balance_balance_free"), table_name="data_asset_balance"
    )
    op.drop_table("data_asset_balance")
    # ### end Alembic commands ###
