"""Added treasury and tech comm tables

Revision ID: 8712ff01cb11
Revises: 9b7c2ca7a3a7
Create Date: 2019-12-20 15:08:56.377010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8712ff01cb11'
down_revision = '9b7c2ca7a3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_techcomm_proposal',
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('motion_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('proposal_hash', sa.String(length=64), nullable=True),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('member_threshold', sa.Integer(), nullable=False),
    sa.Column('yes_votes_count', sa.Integer(), nullable=False),
    sa.Column('no_votes_count', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_index(op.f('ix_data_techcomm_proposal_motion_hash'), 'data_techcomm_proposal', ['motion_hash'], unique=False)
    op.create_table('data_techcomm_proposal_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motion_hash', sa.String(length=64), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_techcomm_proposal_audit_block_id'), 'data_techcomm_proposal_audit', ['block_id'], unique=False)
    op.create_table('data_techcomm_proposal_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('motion_hash', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('vote', sa.Boolean(), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_techcomm_proposal_vote_account_id'), 'data_techcomm_proposal_vote', ['account_id'], unique=False)
    op.create_index(op.f('ix_data_techcomm_proposal_vote_motion_hash'), 'data_techcomm_proposal_vote', ['motion_hash'], unique=False)
    op.create_index(op.f('ix_data_techcomm_proposal_vote_proposal_id'), 'data_techcomm_proposal_vote', ['proposal_id'], unique=False)
    op.create_table('data_techcomm_proposal_vote_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('motion_hash', sa.String(length=64), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_techcomm_proposal_vote_audit_block_id'), 'data_techcomm_proposal_vote_audit', ['block_id'], unique=False)
    op.create_table('data_treasury_proposal',
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('proposed_by_account_id', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('beneficiary_account_id', sa.String(length=64), nullable=True),
    sa.Column('slash_value', sa.Numeric(precision=65, scale=0), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_table('data_treasury_proposal_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_treasury_proposal_audit_block_id'), 'data_treasury_proposal_audit', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_treasury_proposal_audit_block_id'), table_name='data_treasury_proposal_audit')
    op.drop_table('data_treasury_proposal_audit')
    op.drop_table('data_treasury_proposal')
    op.drop_index(op.f('ix_data_techcomm_proposal_vote_audit_block_id'), table_name='data_techcomm_proposal_vote_audit')
    op.drop_table('data_techcomm_proposal_vote_audit')
    op.drop_index(op.f('ix_data_techcomm_proposal_vote_proposal_id'), table_name='data_techcomm_proposal_vote')
    op.drop_index(op.f('ix_data_techcomm_proposal_vote_motion_hash'), table_name='data_techcomm_proposal_vote')
    op.drop_index(op.f('ix_data_techcomm_proposal_vote_account_id'), table_name='data_techcomm_proposal_vote')
    op.drop_table('data_techcomm_proposal_vote')
    op.drop_index(op.f('ix_data_techcomm_proposal_audit_block_id'), table_name='data_techcomm_proposal_audit')
    op.drop_table('data_techcomm_proposal_audit')
    op.drop_index(op.f('ix_data_techcomm_proposal_motion_hash'), table_name='data_techcomm_proposal')
    op.drop_table('data_techcomm_proposal')
    # ### end Alembic commands ###
