"""Proposal Audit table

Revision ID: 904e857e3170
Revises: 2fc15a48a46d
Create Date: 2019-06-26 11:31:29.008082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '904e857e3170'
down_revision = '2fc15a48a46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_democracy_proposal_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('democracy_proposal_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_democracy_proposal_audit_block_id'), 'data_democracy_proposal_audit', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_democracy_proposal_audit_democracy_proposal_id'), 'data_democracy_proposal_audit', ['democracy_proposal_id'], unique=False)
    op.alter_column('data_account_index_audit', 'account_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.add_column('data_democracy_proposal', sa.Column('updated_at_block', sa.Integer(), nullable=False))
    op.drop_column('data_democracy_proposal', 'created_at_extrinsic')
    op.drop_column('data_democracy_proposal', 'created_at_event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_democracy_proposal', sa.Column('created_at_event', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('data_democracy_proposal', sa.Column('created_at_extrinsic', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('data_democracy_proposal', 'updated_at_block')
    op.alter_column('data_account_index_audit', 'account_id',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_index(op.f('ix_data_democracy_proposal_audit_democracy_proposal_id'), table_name='data_democracy_proposal_audit')
    op.drop_index(op.f('ix_data_democracy_proposal_audit_block_id'), table_name='data_democracy_proposal_audit')
    op.drop_table('data_democracy_proposal_audit')
    # ### end Alembic commands ###
