"""Add proposal id to council vote

Revision ID: 9b7c2ca7a3a7
Revises: 0bde1522ffb7
Create Date: 2019-12-11 12:19:14.744460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7c2ca7a3a7'
down_revision = '0bde1522ffb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_council_vote', sa.Column('proposal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_data_council_vote_proposal_id'), 'data_council_vote', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_council_vote_proposal_id'), table_name='data_council_vote')
    op.drop_column('data_council_vote', 'proposal_id')
    # ### end Alembic commands ###
