"""Removed FK

Revision ID: a0e3968eb185
Revises: 7a876737373d
Create Date: 2019-06-24 15:23:59.076214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e3968eb185'
down_revision = '7a876737373d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_block_total_ibfk_1', 'data_block_total', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('data_block_total_ibfk_1', 'data_block_total', 'data_block', ['id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
