"""Added reorg tables

Revision ID: b1946cf50a06
Revises: 7918a883377c
Create Date: 2019-10-01 17:05:34.750231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1946cf50a06'
down_revision = '7918a883377c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_reorg_block',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('state_root', sa.String(length=66), nullable=False),
    sa.Column('extrinsics_root', sa.String(length=66), nullable=False),
    sa.Column('count_extrinsics', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_unsigned', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signed', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_error', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_success', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signedby_address', sa.Integer(), nullable=False),
    sa.Column('count_extrinsics_signedby_index', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('count_events_system', sa.Integer(), nullable=False),
    sa.Column('count_events_module', sa.Integer(), nullable=False),
    sa.Column('count_events_extrinsic', sa.Integer(), nullable=False),
    sa.Column('count_events_finalization', sa.Integer(), nullable=False),
    sa.Column('count_accounts', sa.Integer(), nullable=False),
    sa.Column('count_accounts_new', sa.Integer(), nullable=False),
    sa.Column('count_accounts_reaped', sa.Integer(), nullable=False),
    sa.Column('count_sessions_new', sa.Integer(), nullable=False),
    sa.Column('count_contracts_new', sa.Integer(), nullable=False),
    sa.Column('count_log', sa.Integer(), nullable=False),
    sa.Column('range10000', sa.Integer(), nullable=False),
    sa.Column('range100000', sa.Integer(), nullable=False),
    sa.Column('range1000000', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('full_month', sa.Integer(), nullable=True),
    sa.Column('full_week', sa.Integer(), nullable=True),
    sa.Column('full_day', sa.Integer(), nullable=True),
    sa.Column('full_hour', sa.Integer(), nullable=True),
    sa.Column('logs', sa.JSON(), nullable=True),
    sa.Column('spec_version_id', sa.String(length=64), nullable=False),
    sa.Column('debug_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_reorg_block_hash'), 'data_reorg_block', ['hash'], unique=True)
    op.create_index(op.f('ix_data_reorg_block_parent_hash'), 'data_reorg_block', ['parent_hash'], unique=False)
    op.create_table('data_reorg_event',
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('system', sa.SmallInteger(), nullable=False),
    sa.Column('module', sa.SmallInteger(), nullable=False),
    sa.Column('phase', sa.SmallInteger(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'event_idx')
    )
    op.create_index(op.f('ix_data_reorg_event_block_hash'), 'data_reorg_event', ['block_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_block_id'), 'data_reorg_event', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_event_id'), 'data_reorg_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_event_idx'), 'data_reorg_event', ['event_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_extrinsic_idx'), 'data_reorg_event', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_module'), 'data_reorg_event', ['module'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_module_id'), 'data_reorg_event', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_system'), 'data_reorg_event', ['system'], unique=False)
    op.create_index(op.f('ix_data_reorg_event_type'), 'data_reorg_event', ['type'], unique=False)
    op.create_table('data_reorg_extrinsic',
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_hash', sa.String(length=64), nullable=True),
    sa.Column('extrinsic_length', sa.String(length=10), nullable=True),
    sa.Column('extrinsic_version', sa.String(length=2), nullable=True),
    sa.Column('signed', sa.SmallInteger(), nullable=False),
    sa.Column('unsigned', sa.SmallInteger(), nullable=False),
    sa.Column('signedby_address', sa.SmallInteger(), nullable=False),
    sa.Column('signedby_index', sa.SmallInteger(), nullable=False),
    sa.Column('address_length', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('account_index', sa.String(length=16), nullable=True),
    sa.Column('account_idx', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=4), nullable=True),
    sa.Column('call', sa.String(length=4), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.SmallInteger(), nullable=False),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_data_reorg_extrinsic_account_idx'), 'data_reorg_extrinsic', ['account_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_account_index'), 'data_reorg_extrinsic', ['account_index'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_address'), 'data_reorg_extrinsic', ['address'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_block_hash'), 'data_reorg_extrinsic', ['block_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_block_id'), 'data_reorg_extrinsic', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_call_id'), 'data_reorg_extrinsic', ['call_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_extrinsic_hash'), 'data_reorg_extrinsic', ['extrinsic_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_extrinsic_idx'), 'data_reorg_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_module_id'), 'data_reorg_extrinsic', ['module_id'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_signed'), 'data_reorg_extrinsic', ['signed'], unique=False)
    op.create_index(op.f('ix_data_reorg_extrinsic_unsigned'), 'data_reorg_extrinsic', ['unsigned'], unique=False)
    op.create_table('data_reorg_log',
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('block_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('log_idx', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('block_hash', 'log_idx')
    )
    op.create_index(op.f('ix_data_reorg_log_block_hash'), 'data_reorg_log', ['block_hash'], unique=False)
    op.create_index(op.f('ix_data_reorg_log_type_id'), 'data_reorg_log', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_reorg_log_type_id'), table_name='data_reorg_log')
    op.drop_index(op.f('ix_data_reorg_log_block_hash'), table_name='data_reorg_log')
    op.drop_table('data_reorg_log')
    op.drop_index(op.f('ix_data_reorg_extrinsic_unsigned'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_signed'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_module_id'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_extrinsic_idx'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_extrinsic_hash'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_call_id'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_block_id'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_block_hash'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_address'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_account_index'), table_name='data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_extrinsic_account_idx'), table_name='data_reorg_extrinsic')
    op.drop_table('data_reorg_extrinsic')
    op.drop_index(op.f('ix_data_reorg_event_type'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_system'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_module_id'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_module'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_extrinsic_idx'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_event_idx'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_event_id'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_block_id'), table_name='data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_event_block_hash'), table_name='data_reorg_event')
    op.drop_table('data_reorg_event')
    op.drop_index(op.f('ix_data_reorg_block_parent_hash'), table_name='data_reorg_block')
    op.drop_index(op.f('ix_data_reorg_block_hash'), table_name='data_reorg_block')
    op.drop_table('data_reorg_block')
    # ### end Alembic commands ###
