"""Added runtime error table

Revision ID: b7aade4297e6
Revises: 874a66d2cdfb
Create Date: 2019-10-23 10:18:11.975859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7aade4297e6'
down_revision = '874a66d2cdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runtime_error_name'), 'runtime_error', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runtime_error_name'), table_name='runtime_error')
    op.drop_table('runtime_error')
    # ### end Alembic commands ###
