"""Merged metadata runtime

Revision ID: ba1bdb560610
Revises: 06003b460c7f
Create Date: 2019-06-05 13:45:31.946554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba1bdb560610'
down_revision = '06003b460c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    op.add_column('data_block', sa.Column('logs', sa.JSON(), nullable=True))
    op.add_column('runtime', sa.Column('apis', sa.JSON(), nullable=True))
    op.add_column('runtime', sa.Column('authoring_version', sa.Integer(), nullable=True))
    op.add_column('runtime', sa.Column('count_call_functions', sa.Integer(), nullable=False))
    op.add_column('runtime', sa.Column('count_events', sa.Integer(), nullable=False))
    op.add_column('runtime', sa.Column('count_modules', sa.Integer(), nullable=False))
    op.add_column('runtime', sa.Column('count_storage_functions', sa.Integer(), nullable=False))
    op.add_column('runtime', sa.Column('json_metadata', sa.JSON(), nullable=True))
    op.add_column('runtime', sa.Column('json_metadata_decoded', sa.JSON(), nullable=True))
    op.add_column('runtime', sa.Column('spec_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'runtime', ['spec_version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runtime', type_='unique')
    op.drop_column('runtime', 'spec_name')
    op.drop_column('runtime', 'json_metadata_decoded')
    op.drop_column('runtime', 'json_metadata')
    op.drop_column('runtime', 'count_storage_functions')
    op.drop_column('runtime', 'count_modules')
    op.drop_column('runtime', 'count_events')
    op.drop_column('runtime', 'count_call_functions')
    op.drop_column('runtime', 'authoring_version')
    op.drop_column('runtime', 'apis')
    op.drop_column('data_block', 'logs')
    op.create_table('metadata',
    sa.Column('spec_version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('json_metadata', mysql.JSON(), nullable=True),
    sa.Column('json_metadata_decoded', mysql.JSON(), nullable=True),
    sa.Column('count_call_functions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count_events', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count_modules', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count_storage_functions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('spec_version'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
