"""Added extrinsic hash

Revision ID: c416f4b721bf
Revises: 9f49ad83cdb0
Create Date: 2019-05-09 20:30:28.799648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c416f4b721bf'
down_revision = '9f49ad83cdb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_extrinsic', sa.Column('extrinsic_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_extrinsic_extrinsic_hash'), 'data_extrinsic', ['extrinsic_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_extrinsic_extrinsic_hash'), table_name='data_extrinsic')
    op.drop_column('data_extrinsic', 'extrinsic_hash')
    # ### end Alembic commands ###
