"""Added event indices

Revision ID: cbdc0e347ee5
Revises: 67a2febe1793
Create Date: 2019-05-03 15:13:28.372623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdc0e347ee5'
down_revision = '67a2febe1793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_event_event_id'), 'data_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_data_event_module_id'), 'data_event', ['module_id'], unique=False)
    op.drop_index('data_extrinsic_block_id_index', table_name='data_extrinsic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('data_extrinsic_block_id_index', 'data_extrinsic', ['block_id'], unique=False)
    op.drop_index(op.f('ix_data_event_module_id'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_event_id'), table_name='data_event')
    # ### end Alembic commands ###
