"""Added runtime type model

Revision ID: d0a0f5baeae8
Revises: cbdc0e347ee5
Create Date: 2019-05-06 15:38:35.381625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a0f5baeae8'
down_revision = 'cbdc0e347ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.Column('type_string', sa.String(length=255), nullable=True),
    sa.Column('decoder_class', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_version', 'type_string')
    )
    op.create_index(op.f('ix_data_extrinsic_block_id'), 'data_extrinsic', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_extrinsic_block_id'), table_name='data_extrinsic')
    op.drop_table('runtime_type')
    # ### end Alembic commands ###
