"""Move vote counts to council motion tables

Revision ID: da691ae8609a
Revises: 213043ea4c8f
Create Date: 2019-12-10 18:17:18.241089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da691ae8609a'
down_revision = '213043ea4c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_council_motion', sa.Column('no_votes_count', sa.Integer(), nullable=False))
    op.add_column('data_council_motion', sa.Column('yes_votes_count', sa.Integer(), nullable=False))
    op.drop_column('data_council_vote', 'yes_votes_count')
    op.drop_column('data_council_vote', 'no_votes_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_council_vote', sa.Column('no_votes_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('data_council_vote', sa.Column('yes_votes_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('data_council_motion', 'yes_votes_count')
    op.drop_column('data_council_motion', 'no_votes_count')
    # ### end Alembic commands ###
