"""Validator and nominator changes

Revision ID: e51020d747ec
Revises: 1e6da577c3aa
Create Date: 2019-07-30 22:23:34.795007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e51020d747ec'
down_revision = '1e6da577c3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_session_nominator', sa.Column('bonded', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_nominator', sa.Column('nominator_controller', sa.String(length=64), nullable=True))
    op.add_column('data_session_nominator', sa.Column('nominator_stash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_session_nominator_nominator_controller'), 'data_session_nominator', ['nominator_controller'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_nominator_stash'), 'data_session_nominator', ['nominator_stash'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_rank_nominator'), 'data_session_nominator', ['rank_nominator'], unique=False)
    op.create_index(op.f('ix_data_session_nominator_rank_validator'), 'data_session_nominator', ['rank_validator'], unique=False)
    op.drop_index('ix_data_session_nominator_nominator', table_name='data_session_nominator')
    op.drop_index('ix_data_session_nominator_validator', table_name='data_session_nominator')
    op.drop_column('data_session_nominator', 'nominator')
    op.drop_column('data_session_nominator', 'validator')
    op.add_column('data_session_validator', sa.Column('bonded_active', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('bonded_nominators', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('bonded_own', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('bonded_total', sa.Numeric(precision=65, scale=0), nullable=False))
    op.add_column('data_session_validator', sa.Column('unlocking', sa.JSON(), nullable=True))
    op.add_column('data_session_validator', sa.Column('validator_controller', sa.String(length=64), nullable=True))
    op.add_column('data_session_validator', sa.Column('validator_session', sa.String(length=64), nullable=True))
    op.add_column('data_session_validator', sa.Column('validator_stash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_data_session_validator_rank_validator'), 'data_session_validator', ['rank_validator'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_controller'), 'data_session_validator', ['validator_controller'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_session'), 'data_session_validator', ['validator_session'], unique=False)
    op.create_index(op.f('ix_data_session_validator_validator_stash'), 'data_session_validator', ['validator_stash'], unique=False)
    op.drop_index('ix_data_session_validator_validator', table_name='data_session_validator')
    op.drop_column('data_session_validator', 'validator')

    op.drop_constraint('PRIMARY', 'data_session_nominator', type_='primary')
    op.create_primary_key("data_session_nominator_pk", "data_session_nominator",
                          ["session_id", "rank_validator", "rank_nominator"])

    op.drop_constraint('PRIMARY', 'data_session_validator', type_='primary')
    op.create_primary_key("data_session_validator_pk", "data_session_validator",
                          ["session_id", "rank_validator"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_session_validator', sa.Column('validator', mysql.VARCHAR(length=64), nullable=False))
    op.create_index('ix_data_session_validator_validator', 'data_session_validator', ['validator'], unique=False)
    op.drop_index(op.f('ix_data_session_validator_validator_stash'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_validator_session'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_validator_controller'), table_name='data_session_validator')
    op.drop_index(op.f('ix_data_session_validator_rank_validator'), table_name='data_session_validator')
    op.drop_column('data_session_validator', 'validator_stash')
    op.drop_column('data_session_validator', 'validator_session')
    op.drop_column('data_session_validator', 'validator_controller')
    op.drop_column('data_session_validator', 'unlocking')
    op.drop_column('data_session_validator', 'bonded_total')
    op.drop_column('data_session_validator', 'bonded_own')
    op.drop_column('data_session_validator', 'bonded_nominators')
    op.drop_column('data_session_validator', 'bonded_active')
    op.add_column('data_session_nominator', sa.Column('validator', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('data_session_nominator', sa.Column('nominator', mysql.VARCHAR(length=64), nullable=False))
    op.create_index('ix_data_session_nominator_validator', 'data_session_nominator', ['validator'], unique=False)
    op.create_index('ix_data_session_nominator_nominator', 'data_session_nominator', ['nominator'], unique=False)
    op.drop_index(op.f('ix_data_session_nominator_rank_validator'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_rank_nominator'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_nominator_stash'), table_name='data_session_nominator')
    op.drop_index(op.f('ix_data_session_nominator_nominator_controller'), table_name='data_session_nominator')
    op.drop_column('data_session_nominator', 'nominator_stash')
    op.drop_column('data_session_nominator', 'nominator_controller')
    op.drop_column('data_session_nominator', 'bonded')
    # ### end Alembic commands ###
