"""Validator nullable fields

Revision ID: eab2bca0e472
Revises: fe731dd01fdf
Create Date: 2019-07-31 19:17:46.915579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eab2bca0e472'
down_revision = 'fe731dd01fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_session_nominator', 'bonded',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=True)
    op.alter_column('data_session_validator', 'bonded_active',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=True)
    op.alter_column('data_session_validator', 'bonded_nominators',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=True)
    op.alter_column('data_session_validator', 'bonded_own',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=True)
    op.alter_column('data_session_validator', 'bonded_total',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_session_validator', 'bonded_total',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=False)
    op.alter_column('data_session_validator', 'bonded_own',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=False)
    op.alter_column('data_session_validator', 'bonded_nominators',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=False)
    op.alter_column('data_session_validator', 'bonded_active',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=False)
    op.alter_column('data_session_nominator', 'bonded',
               existing_type=mysql.DECIMAL(precision=65, scale=0),
               nullable=False)
    # ### end Alembic commands ###
