"""Added Account Session Contract Log models

Revision ID: eb9113e36e1e
Revises: 3abfab7edea8
Create Date: 2019-06-14 13:47:37.279319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb9113e36e1e'
down_revision = '3abfab7edea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_account',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=48), nullable=True),
    sa.Column('balance_at_creation', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('created_at_block', sa.Integer(), nullable=True),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.Column('referenced_at_block', sa.Integer(), nullable=True),
    sa.Column('reaped_at_block', sa.Integer(), nullable=True),
    sa.Column('reaped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_address'), 'data_account', ['address'], unique=False)
    op.create_table('data_account_index',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('account_at_creation', sa.String(length=64), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=True),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.Column('referenced_at_block', sa.Integer(), nullable=True),
    sa.Column('reaped_at_block', sa.Integer(), nullable=True),
    sa.Column('reaped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_account_index_account'), 'data_account_index', ['account'], unique=False)
    op.create_table('data_contract',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('bytecode', mysql.LONGTEXT(), nullable=True),
    sa.Column('source', mysql.LONGTEXT(), nullable=True),
    sa.Column('abi', sa.JSON(), nullable=True),
    sa.Column('compiler', sa.String(length=64), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_table('data_democracy_proposal',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('bond', sa.Numeric(precision=65, scale=0), nullable=False),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_log',
    sa.Column('block_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('log_idx', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'log_idx')
    )
    op.create_table('data_session',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('start_at_block', sa.Integer(), nullable=True),
    sa.Column('end_at_block', sa.Integer(), nullable=True),
    sa.Column('era', sa.Integer(), nullable=True),
    sa.Column('era_idx', sa.Integer(), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('created_at_extrinsic', sa.Integer(), nullable=True),
    sa.Column('created_at_event', sa.Integer(), nullable=True),
    sa.Column('count_blocks', sa.Integer(), nullable=True),
    sa.Column('count_validators', sa.Integer(), nullable=True),
    sa.Column('count_nominators', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_session')
    op.drop_table('data_log')
    op.drop_table('data_democracy_proposal')
    op.drop_table('data_contract')
    op.drop_index(op.f('ix_data_account_index_account'), table_name='data_account_index')
    op.drop_table('data_account_index')
    op.drop_index(op.f('ix_data_account_address'), table_name='data_account')
    op.drop_table('data_account')
    # ### end Alembic commands ###
