"""Initial models

Revision ID: ecddcc48bd7a
Revises: 
Create Date: 2019-04-06 12:41:48.439444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecddcc48bd7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_block',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('state_root', sa.String(length=66), nullable=False),
    sa.Column('extrinsics_root', sa.String(length=66), nullable=False),
    sa.Column('count_extrinsics', sa.Integer(), nullable=False),
    sa.Column('count_events', sa.Integer(), nullable=False),
    sa.Column('spec_version_id', sa.String(length=64), nullable=False),
    sa.Column('debug_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_block_hash'), 'data_block', ['hash'], unique=True)
    op.create_index(op.f('ix_data_block_parent_hash'), 'data_block', ['parent_hash'], unique=False)
    op.create_table('data_event',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('event_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=4), nullable=True),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('system', sa.SmallInteger(), nullable=False),
    sa.Column('module', sa.SmallInteger(), nullable=False),
    sa.Column('phase', sa.SmallInteger(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'event_idx')
    )
    op.create_index(op.f('ix_data_event_extrinsic_idx'), 'data_event', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_event_module'), 'data_event', ['module'], unique=False)
    op.create_index(op.f('ix_data_event_system'), 'data_event', ['system'], unique=False)
    op.create_index(op.f('ix_data_event_type'), 'data_event', ['type'], unique=False)
    op.create_table('data_extrinsic',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=False),
    sa.Column('extrinsic_length', sa.String(length=10), nullable=True),
    sa.Column('extrinsic_version', sa.String(length=2), nullable=True),
    sa.Column('signed', sa.SmallInteger(), nullable=False),
    sa.Column('unsigned', sa.SmallInteger(), nullable=False),
    sa.Column('address_length', sa.String(length=2), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('account_index', sa.String(length=16), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=4), nullable=True),
    sa.Column('call', sa.String(length=4), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('call_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('success', sa.SmallInteger(), nullable=False),
    sa.Column('error', sa.SmallInteger(), nullable=False),
    sa.Column('spec_version_id', sa.Integer(), nullable=True),
    sa.Column('codec_error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('block_id', 'extrinsic_idx')
    )
    op.create_index(op.f('ix_data_extrinsic_call_id'), 'data_extrinsic', ['call_id'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_extrinsic_idx'), 'data_extrinsic', ['extrinsic_idx'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_signed'), 'data_extrinsic', ['signed'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_unsigned'), 'data_extrinsic', ['unsigned'], unique=False)
    op.create_table('metadata',
    sa.Column('spec_version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('json_metadata', sa.JSON(), nullable=True),
    sa.Column('json_metadata_decoded', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('spec_version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    op.drop_index(op.f('ix_data_extrinsic_unsigned'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_signed'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_extrinsic_idx'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_call_id'), table_name='data_extrinsic')
    op.drop_table('data_extrinsic')
    op.drop_index(op.f('ix_data_event_type'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_system'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_module'), table_name='data_event')
    op.drop_index(op.f('ix_data_event_extrinsic_idx'), table_name='data_event')
    op.drop_table('data_event')
    op.drop_index(op.f('ix_data_block_parent_hash'), table_name='data_block')
    op.drop_index(op.f('ix_data_block_hash'), table_name='data_block')
    op.drop_table('data_block')
    # ### end Alembic commands ###
