"""Validator payment prefs

Revision ID: fe731dd01fdf
Revises: c01c84756142
Create Date: 2019-07-31 12:02:47.756219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe731dd01fdf'
down_revision = 'c01c84756142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_session_validator', sa.Column('commission', sa.Numeric(precision=65, scale=0), nullable=True))
    op.add_column('data_session_validator', sa.Column('unstake_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_session_validator', 'unstake_threshold')
    op.drop_column('data_session_validator', 'commission')
    # ### end Alembic commands ###
