"""Added referendum tables

Revision ID: fea3e3c2e1d3
Revises: 7d3a5a5ef6c2
Create Date: 2019-07-05 11:46:44.681036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea3e3c2e1d3'
down_revision = '7d3a5a5ef6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_democracy_referendum',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('proposal', sa.JSON(), nullable=True),
    sa.Column('vote_threshold', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at_block', sa.Integer(), nullable=False),
    sa.Column('updated_at_block', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_democracy_referendum_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('democracy_referendum_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('extrinsic_idx', sa.Integer(), nullable=True),
    sa.Column('event_idx', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_democracy_referendum_audit_block_id'), 'data_democracy_referendum_audit', ['block_id'], unique=False)
    op.create_index(op.f('ix_data_democracy_referendum_audit_democracy_referendum_id'), 'data_democracy_referendum_audit', ['democracy_referendum_id'], unique=False)
    op.add_column('data_block_total', sa.Column('author', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_block_total', 'author')
    op.drop_index(op.f('ix_data_democracy_referendum_audit_democracy_referendum_id'), table_name='data_democracy_referendum_audit')
    op.drop_index(op.f('ix_data_democracy_referendum_audit_block_id'), table_name='data_democracy_referendum_audit')
    op.drop_table('data_democracy_referendum_audit')
    op.drop_table('data_democracy_referendum')
    # ### end Alembic commands ###
