"""Added account indices

Revision ID: fed48c78b8b6
Revises: ecddcc48bd7a
Create Date: 2019-04-14 13:44:28.644276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed48c78b8b6'
down_revision = 'ecddcc48bd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_data_extrinsic_account_index'), 'data_extrinsic', ['account_index'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_address'), 'data_extrinsic', ['address'], unique=False)
    op.create_index(op.f('ix_data_extrinsic_module_id'), 'data_extrinsic', ['module_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_extrinsic_module_id'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_address'), table_name='data_extrinsic')
    op.drop_index(op.f('ix_data_extrinsic_account_index'), table_name='data_extrinsic')
    # ### end Alembic commands ###
